-- 数据库索引优化SQL
-- 生成时间: 2026-02-05 18:16:50.789176
-- 说明: 这些索引用于优化常用查询字段的性能

CREATE INDEX IF NOT EXISTS idx_order_order_number ON orders (order_number); -- 订单号查询
CREATE INDEX IF NOT EXISTS idx_order_status ON orders (status); -- 订单状态查询
CREATE INDEX IF NOT EXISTS idx_order_created_at ON orders (created_at); -- 创建时间排序
CREATE INDEX IF NOT EXISTS idx_order_franchisee_id ON orders (franchisee_id); -- 加盟商订单查询
CREATE INDEX IF NOT EXISTS idx_order_merchant_id ON orders (merchant_id); -- 商户订单查询
CREATE INDEX IF NOT EXISTS idx_order_openid ON orders (openid); -- 用户订单查询
CREATE INDEX IF NOT EXISTS idx_order_customer_phone ON orders (customer_phone); -- 客户电话查询
CREATE INDEX IF NOT EXISTS idx_order_completed_at ON orders (completed_at); -- 完成时间查询
CREATE INDEX IF NOT EXISTS idx_order_source_type ON orders (source_type); -- 来源类型查询
CREATE INDEX IF NOT EXISTS idx_order_order_mode ON orders (order_mode); -- 订单模式查询
CREATE INDEX IF NOT EXISTS idx_aitask_order_id ON aitasks (order_id); -- 订单关联查询
CREATE INDEX IF NOT EXISTS idx_aitask_status ON aitasks (status); -- 任务状态查询
CREATE INDEX IF NOT EXISTS idx_aitask_created_at ON aitasks (created_at); -- 创建时间排序
CREATE INDEX IF NOT EXISTS idx_aitask_order_number ON aitasks (order_number); -- 订单号查询
CREATE INDEX IF NOT EXISTS idx_aitask_style_category_id ON aitasks (style_category_id); -- 风格分类查询
CREATE INDEX IF NOT EXISTS idx_aitask_style_image_id ON aitasks (style_image_id); -- 风格图片查询
CREATE INDEX IF NOT EXISTS idx_aitask_completed_at ON aitasks (completed_at); -- 完成时间查询
CREATE INDEX IF NOT EXISTS idx_orderimage_is_main ON orderimages (is_main); -- 主图查询
CREATE INDEX IF NOT EXISTS idx_product_is_active ON products (is_active); -- 激活产品查询
CREATE INDEX IF NOT EXISTS idx_product_category_id ON products (category_id); -- 分类查询
CREATE INDEX IF NOT EXISTS idx_product_subcategory_id ON products (subcategory_id); -- 子分类查询
CREATE INDEX IF NOT EXISTS idx_product_sort_order ON products (sort_order); -- 排序查询
CREATE INDEX IF NOT EXISTS idx_productsize_product_id ON productsizes (product_id); -- 产品尺寸查询
CREATE INDEX IF NOT EXISTS idx_productsize_is_active ON productsizes (is_active); -- 激活尺寸查询
CREATE INDEX IF NOT EXISTS idx_productimage_product_id ON productimages (product_id); -- 产品图片查询
CREATE INDEX IF NOT EXISTS idx_productimage_is_active ON productimages (is_active); -- 激活图片查询
CREATE INDEX IF NOT EXISTS idx_productstylecategory_product_id ON productstylecategories (product_id); -- 产品风格绑定查询
CREATE INDEX IF NOT EXISTS idx_productstylecategory_style_category_id ON productstylecategories (style_category_id); -- 风格分类绑定查询
CREATE INDEX IF NOT EXISTS idx_stylecategory_is_active ON stylecategories (is_active); -- 激活风格查询
CREATE INDEX IF NOT EXISTS idx_stylecategory_sort_order ON stylecategories (sort_order); -- 排序查询
CREATE INDEX IF NOT EXISTS idx_styleimage_category_id ON styleimages (category_id); -- 风格分类图片查询
CREATE INDEX IF NOT EXISTS idx_styleimage_is_active ON styleimages (is_active); -- 激活图片查询
CREATE INDEX IF NOT EXISTS idx_franchiseeaccount_status ON franchiseeaccounts (status); -- 账户状态查询
CREATE INDEX IF NOT EXISTS idx_franchiseeaccount_username ON franchiseeaccounts (username); -- 用户名查询
CREATE INDEX IF NOT EXISTS idx_franchiseeaccount_qr_code ON franchiseeaccounts (qr_code); -- 二维码查询
CREATE INDEX IF NOT EXISTS idx_franchiseerecharge_franchisee_id ON franchiseerecharges (franchisee_id); -- 加盟商充值记录查询
CREATE INDEX IF NOT EXISTS idx_franchiseerecharge_created_at ON franchiseerecharges (created_at); -- 创建时间排序
CREATE INDEX IF NOT EXISTS idx_shoporder_order_number ON shoporders (order_number); -- 订单号查询
CREATE INDEX IF NOT EXISTS idx_shoporder_original_order_id ON shoporders (original_order_id); -- 原始订单查询
CREATE INDEX IF NOT EXISTS idx_shoporder_original_order_number ON shoporders (original_order_number); -- 原始订单号查询
CREATE INDEX IF NOT EXISTS idx_shoporder_status ON shoporders (status); -- 订单状态查询
CREATE INDEX IF NOT EXISTS idx_shoporder_product_id ON shoporders (product_id); -- 产品查询
CREATE INDEX IF NOT EXISTS idx_shopproduct_is_active ON shopproducts (is_active); -- 激活产品查询
CREATE INDEX IF NOT EXISTS idx_shopproduct_sort_order ON shopproducts (sort_order); -- 排序查询
CREATE INDEX IF NOT EXISTS idx_shopproductsize_product_id ON shopproductsizes (product_id); -- 产品尺寸查询
CREATE INDEX IF NOT EXISTS idx_shopproductsize_is_active ON shopproductsizes (is_active); -- 激活尺寸查询
CREATE INDEX IF NOT EXISTS idx_shopproductimage_product_id ON shopproductimages (product_id); -- 产品图片查询
CREATE INDEX IF NOT EXISTS idx_shopproductimage_is_active ON shopproductimages (is_active); -- 激活图片查询
CREATE INDEX IF NOT EXISTS idx_coupon_status ON coupons (status); -- 优惠券状态查询
CREATE INDEX IF NOT EXISTS idx_coupon_source_type ON coupons (source_type); -- 来源类型查询
CREATE INDEX IF NOT EXISTS idx_usercoupon_user_id ON usercoupons (user_id); -- 用户优惠券查询
CREATE INDEX IF NOT EXISTS idx_usercoupon_coupon_id ON usercoupons (coupon_id); -- 优惠券查询
CREATE INDEX IF NOT EXISTS idx_usercoupon_status ON usercoupons (status); -- 状态查询
CREATE INDEX IF NOT EXISTS idx_promotionuser_promotion_code ON promotionusers (promotion_code); -- 推广码查询
CREATE INDEX IF NOT EXISTS idx_promotionuser_open_id ON promotionusers (open_id); -- 用户查询
CREATE INDEX IF NOT EXISTS idx_promotionuser_user_id ON promotionusers (user_id); -- 用户ID查询
CREATE INDEX IF NOT EXISTS idx_commission_user_id ON commissions (user_id); -- 用户佣金查询
CREATE INDEX IF NOT EXISTS idx_commission_order_id ON commissions (order_id); -- 订单佣金查询
CREATE INDEX IF NOT EXISTS idx_commission_status ON commissions (status); -- 状态查询
CREATE INDEX IF NOT EXISTS idx_uservisit_user_id ON uservisits (user_id); -- 用户访问查询
CREATE INDEX IF NOT EXISTS idx_uservisit_visit_time ON uservisits (visit_time); -- 访问时间查询
CREATE INDEX IF NOT EXISTS idx_uservisit_is_authorized ON uservisits (is_authorized); -- 授权状态查询
CREATE INDEX IF NOT EXISTS idx_selfiemachine_franchisee_id ON selfiemachines (franchisee_id); -- 加盟商设备查询
CREATE INDEX IF NOT EXISTS idx_selfiemachine_machine_serial_number ON selfiemachines (machine_serial_number); -- 设备序列号查询
